#!/bin/bash

# fzf fuzzy search of git repositories, then clone
function fclonesesh() {

    repo="$( \
        (cat $fzf_git_cache 2>/dev/null; $HOME/scripts/listrepo_gql $GITHUB_SEARCH_OAUTH_TOKEN $GITHUB_ORG) | \
        tee $fzf_git_cache | \
        nauniq | \
        gum filter --limit 1 --placeholder 'Clone a repo' --height 50 --prompt='🤖 '
    )"

    if [[ -n $repo ]]; then
       username="${repo%%/*}"  # Extracts the username part before '/'
       repo_dir="$HOME/code/$repo"

       if [ -d "$repo_dir" ]; then
          echo "Directory $repo_dir already exists. Connecting..."
          sesh connect $repo_dir
       else
          mkdir -p "$HOME/code/$username"  # Create directory for the username if it doesn't exist

          echo "Cloning from Github into $repo_dir"
          sesh clone -d $HOME/code/$username git@github.com:$repo.git
       fi
    fi
}

fclonesesh
